module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  aos: 0
  auto_entitylabel: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_class: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_font: 0
  color: 0
  comment: 0
  commerce: 0
  commerce_add_to_cart_link: 0
  commerce_cart: 0
  commerce_number_pattern: 0
  commerce_order: 0
  commerce_price: 0
  commerce_product: 0
  commerce_stock: 0
  commerce_store: 0
  config: 0
  config_filter: 0
  config_ignore: 0
  config_split: 0
  contact: 0
  contextual: 0
  ctools: 0
  custom_layout: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  devel: 0
  dropzonejs: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_clone: 0
  entity_reference_revisions: 0
  feeds: 0
  field: 0
  field_group: 0
  field_layout: 0
  field_ui: 0
  file: 0
  filter: 0
  fontawesome: 0
  google_tag: 0
  help: 0
  history: 0
  honeypot: 0
  image: 0
  inline_entity_form: 0
  layout_builder: 0
  layout_builder_modal: 0
  layout_builder_restrictions: 0
  layout_discovery: 0
  link: 0
  mailsystem: 0
  media: 0
  media_bulk_upload: 0
  media_entity_actions: 0
  media_library: 0
  media_library_form_element: 0
  media_library_theme_reset: 0
  menu_block: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  mirror_twin_custom_blocks: 0
  mirrortwin_menu: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  path_alias: 0
  profile: 0
  quickedit: 0
  rabbit_hole: 0
  rdf: 0
  responsive_favicons: 0
  responsive_image: 0
  rh_node: 0
  rh_taxonomy: 0
  rh_user: 0
  search: 0
  shortcut: 0
  simple_instagram_feed: 0
  simple_sitemap: 0
  simple_sitemap_engines: 0
  simple_sitemap_views: 0
  simplenews: 0
  sitewide_alert: 0
  smtp: 0
  state_machine: 0
  svg_image: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  update: 0
  upgrade_status: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  view_unpublished: 0
  views_ajax_history: 0
  views_ui: 0
  viewsreference: 0
  webform: 0
  webform_ui: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  standard: 1000
theme:
  stable: 0
  classy: 0
  bartik: 0
  claro: 0
  mirrortwin: 0
  zurb_foundation: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
