features:
  node_user_picture: 1
  comment_user_picture: 1
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 1
favicon:
  use_default: 1
showcase_link: /showcase
social_instagram: 'https://www.instagram.com/mirrortwinbrewing/?hl=en'
social_twitter: ''
social_behance: ''
zurb_foundation_status_in_reveal: 0
zurb_foundation_use_respondjs: 0
zurb_foundation_meta_header_grid: 0
zurb_foundation_top_bar_enable: '1'
zurb_foundation_top_bar_grid: 0
zurb_foundation_top_bar_sticky: 0
zurb_foundation_top_bar_is_hover: 1
zurb_foundation_top_bar_menu_text: Menu
zurb_foundation_top_bar_custom_back_text: 1
zurb_foundation_top_bar_back_text: Back
zurb_foundation_top_bar_search: 0
zurb_foundation_page_account_info: 0
zurb_foundation_block_copyright_show: 1
zurb_foundation_block_copyright_custom_text: 0
zurb_foundation_block_copyright_text: ''
zurb_foundation_disable_base_css: 0
zurb_foundation_disable_base_js: 0
