_core:
  default_config_hash: 2v5R3I9tNatGzKQjuZWh1y_955xK09313Vn-IIuedyI
smtp_on: false
smtp_host: smtp-relay.sendinblue.com
smtp_hostbackup: ''
smtp_port: '587'
smtp_protocol: standard
smtp_autotls: false
smtp_timeout: 30
smtp_username: jmstewart00@gmail.com
smtp_password: Z1YH7z0MymGAQ39E
smtp_from: no-reply@mirrortwinbrewing.com
smtp_fromname: 'Mirror Twin Brewing'
smtp_client_hostname: ''
smtp_client_helo: ''
smtp_allowhtml: '1'
smtp_test_address: ''
smtp_debugging: false
prev_mail_system: php_mail
smtp_keepalive: false
